import { promises as fs } from 'node:fs';
import path from 'node:path';
import { Eta } from 'eta';

const VIEWS_ROOT = path.join(process.cwd(), 'src', 'routes');
const OUTPUT_DIR = path.join(process.cwd(), 'src', 'lib', 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'eta-templates.ts');

// ponytail: naive recursive walk; the template count is tiny (<<50), no need for a streaming walker.
async function collectEtaFiles(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (full === OUTPUT_DIR) continue;
      files.push(...await collectEtaFiles(full));
    } else if (entry.isFile() && entry.name.endsWith('.eta')) {
      files.push(full);
    }
  }
  return files;
}

function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

async function main(): Promise<void> {
  const files = await collectEtaFiles(VIEWS_ROOT);

  // Build the set of directories under the views root so we can register every
  // relative include key an in-memory template might be looked up by.
  const dirs = new Set<string>([VIEWS_ROOT]);
  for (const file of files) {
    let dir = path.dirname(file);
    while (dir.startsWith(VIEWS_ROOT)) {
      dirs.add(dir);
      if (dir === VIEWS_ROOT) break;
      dir = path.dirname(dir);
    }
  }

  const eta = new Eta();
  const bodies: Record<string, string> = {};

  for (const file of files) {
    const source = await fs.readFile(file, 'utf8');
    const body = eta.compileToString(source);

    const viewsRel = toPosix(path.relative(VIEWS_ROOT, file));
    const keys = new Set<string>([viewsRel, `./${viewsRel}`]);
    for (const dir of dirs) {
      const rel = toPosix(path.relative(dir, file));
      keys.add(rel);
      keys.add(`./${rel}`);
    }

    for (const key of keys) {
      bodies[key] = body;
    }
  }

  const contents = `// AUTO-GENERATED by scripts/build-eta-templates.ts. Do not edit by hand.
// Regenerate with: npm run build:templates
export const compiledTemplateBodies: Record<string, string> = ${JSON.stringify(bodies, null, 2)};
`;

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  await fs.writeFile(OUTPUT_FILE, contents, 'utf8');

  console.log(`Compiled ${files.length} Eta templates into ${Object.keys(bodies).length} in-memory keys at ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
